<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Resume extends Model
{
    protected $guarded = [];
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function templates(){
        return $this->belongsTo("App\Template");
    }

    public function checkCode($random){
        while(!Resume::select('code')->where('code','like',$random.'%')->get()->isEmpty()){
            $random = Str::random(28);
        }
        return $random;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function($model){
            $model->code = $model->checkCode(Str::random(16));
        });
        static::updating(function($model){
            if($model->code == null)
                $model->code = $model->checkCode(Str::random(16));
        });
    }
}
